// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-lsAPfbWUq9L2qhbp0ApUckmnTBwvJI',
    appId: '1:40266981542:web:9b1c61778e5390b104d467',
    messagingSenderId: '40266981542',
    projectId: 'walls-3a403',
    authDomain: 'walls-3a403.firebaseapp.com',
    storageBucket: 'walls-3a403.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ZGFSFzvVOrWGvaVriKzmK7LJTF7JirU',
    appId: '1:40266981542:android:812ce16e468c204b04d467',
    messagingSenderId: '40266981542',
    projectId: 'walls-3a403',
    storageBucket: 'walls-3a403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc4LxHJGADlgnSojY3LakkM-8vCoglb8s',
    appId: '1:40266981542:ios:31b106c29c12816e04d467',
    messagingSenderId: '40266981542',
    projectId: 'walls-3a403',
    storageBucket: 'walls-3a403.appspot.com',
    androidClientId: '40266981542-8rr1m6o926ven25cooa7hj2ia6tq75v7.apps.googleusercontent.com',
    iosClientId: '40266981542-lp710ki1qvmiis83tohjlqi6lctov54b.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallPaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc4LxHJGADlgnSojY3LakkM-8vCoglb8s',
    appId: '1:40266981542:ios:97bab0c48b72b09c04d467',
    messagingSenderId: '40266981542',
    projectId: 'walls-3a403',
    storageBucket: 'walls-3a403.appspot.com',
    androidClientId: '40266981542-8rr1m6o926ven25cooa7hj2ia6tq75v7.apps.googleusercontent.com',
    iosClientId: '40266981542-tbc6kp9gf3klgv5877f1qc87bucb7ij9.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallPaper.RunnerTests',
  );
}
